### ISSUE TITLE
Tumeken's Shadow

### ISSUE THREAD

**Issue by MoonWolf125** [geheur/weapon-charges#14]
Me again!

Was lucky enough to pull the Shadow from TOA the other night. Here's the logs for that exchange. I obtained the Shadow, attempted to wield it (requires charges to wield), left the treasure room, charged the Shadow (Plugin debug mode caught the usage) with 1 charge (1 chaos rune, 1 soul rune), then used it on a Desert Wolf to obtain which animation it was using (9493 I presume), recharged it with a single charge, used it on another Desert Wolf, and then promptly sold it:

[Tumeken's_Shadow_All_Logs.log](https://github.com/geheur/weapon-charges/files/9441448/Tumeken.s_Shadow_All_Logs.log)

**Comment by geheur** [comment]
haha thanks for grabbing that before selling it. and gratz on being a BILLIONAIRE.

**Comment by MoonWolf125** [comment]
Absolutely! Glad to help contribute and thanks 😆 It was a six way split.

**Comment by geheur** [comment]
What is this?
`2022-08-26 19:58:23 [Client] INFO  com.weaponcharges.Devtools - 45179: GAMEMESSAGE "Tumeken's Shadow has no charges! You need to charge it with soul runes and chaos runes."
`
Is this the result of choosing "Charge" on the uncharged staff?

Also I'm not sure I can do anything without a "check" message unfortunately, which I don't see in this log.

**Comment by MoonWolf125** [comment]
Crap. I knew I was forgetting something. Yeah, there's no _check_ message.

That snippet message however is what happens when you try to wield the staff without it having any charges.

**Comment by geheur** [comment]
@nkacena if you can get me the "check" message (the one that pops up when you check charges) I could add it.

**Comment by nkacena** [comment]
@geheur "Tumeken's shadow has x charges remaining." Is this what you mean?

**Comment by nkacena** [comment]
hey was just using it for TOA tele's, could you also do the pharaoh's sceptre?
"Your sceptre has x charges left."

**Comment by MoonWolf125** [comment]
A previous Equipment request was already replied too [here](https://github.com/geheur/weapon-charges/issues/6#issuecomment-1148074197)

> non-combat gear - no plans atm and if I did it would likely be part of a different plugin because most of those aren't weapons ;).

I will have a corresponding log file for the Shadow here in a second @geheur, friend of mine sold his Torva for Shadow to get the cosmetics for ToA gear.

**Comment by MoonWolf125** [comment]
Here's the log, I apologize for not cleaning it up. It should have everything in it this time!
[client.log](https://github.com/geheur/weapon-charges/files/9843655/client.log)

**Comment by geheur** [comment]
https://github.com/runelite/plugin-hub/pull/3487 This should add tumeken's shadow hopefully.

btw @MoonWolf125 do you remember what this message is from? `2022-10-22 00:35:46 [Client] INFO  com.weaponcharges.Devtools - 234713: GAMEMESSAGE "Tumeken's Shadow has no charges! You need to charge it with soul runes and chaos runes."` I don't see any logging of a "check" message (but I think that might not be logged right sometimes, maybe when you "check" an equipped weapon? idr and can't test atm.).

**Comment by MoonWolf125** [comment]
Yes, I believed I answered it [above](https://github.com/geheur/weapon-charges/issues/14#issuecomment-1230816554)

> That snippet message however is what happens when you try to wield the staff without it having any charges.

The first option on the Shadow when it's uncharged is `Wield` and when you attempt to `Wield` it without charges, that is the message that's shown.

**Comment by MoonWolf125** [comment]
I'll see if I can get a chance to test the changes this weekend or if @nkacena would like to give it a try!

**Comment by nkacena** [comment]
all i should have to do is right click check charges and then it should pop up on the shadow right? doesn't look like its working yet. I even tried to uninstall and re-install the app just in case it didnt update.

**Comment by geheur** [comment]
@nkacena It will be available in 0.4.3 which is not released yet. It will be released when the PR I linked (https://github.com/runelite/plugin-hub/pull/3487) is "Merged" instead of "Open".
