### ISSUE TITLE
Blowpipe darts decrementing incorrectly with range skillcape

### ISSUE THREAD

**Issue by IsaacGraham** [geheur/weapon-charges#17]
The plugin is decrementing my darts count as if I'm not wearing an avas when I use it with range skillcape w/vork head.

**Comment by geheur** [comment]
@LlemonDuck oh no the trimmed cape was missing 😱 or er, the `RANGING_CAPET` lol.

Should be an easy fix though :) ty for reporting this.

**Comment by geheur** [comment]
I've added the trimmed range cape, as well as the option to shift-right-click the ranged cape to select whether you've used vorkath's head on it. It will be available in 0.4.3 when that is approved on the hub.
