### ISSUE TITLE
Individual weapon charges removed post update

### ISSUE THREAD

**Issue by Gollum69** [geheur/weapon-charges#28]
I don't know whether it was intentional or not but the individual weapon charges are now gone where you could customise each and every weapon for when the charge count is declared low or empty. Currently they've all been removed and personally I edited all the weapons to flag when they had slightly higher charges please could you bring this back love u

**Comment by geheur** [comment]
They're available as a shift-right-click option on the weapon.

**Comment by Gollum69** [comment]
surely the way it was before was significantly easier, you could just change all the weapons there and then on the plugin settings instead of getting every weapon out individually and shift clicking, also was much easier to keep track

**Comment by Gollum69** [comment]
i suppose it is more of a set and forget type of thing, but it does make it much easier to see what the charges are set at, since personally the default setting is a bit low, i'd prefer to recharge my charges before it hits the low threshold on most weapons tbh
