### ISSUE TITLE
Charges no longer updating passively

### ISSUE THREAD

**Issue by Equanimous** [geheur/weapon-charges#36]
Displayed charges are no longer updating passively. Every item has to be force-updated by right clicking and selecting 'Check', otherwise the number of charges displayed stays the same.  I believe this issue began either with the Leagues IV patch or the one the week prior.

**Comment by qlimaxist** [comment]
same here, already had my charges gone in the middle of contents because of it lol

**Comment by geheur** [comment]
yeah I did something dumb and completely broke it. There is an update (0.6.1) awaiting approval which works fine afaict. Sorry for the interruption :/

**Comment by Equanimous** [comment]
No worries at all man. Appreciate your work :)
