### ISSUE TITLE
Toxic Blowpipe no longer displays scale amount

### ISSUE THREAD

**Issue by Equanimous** [geheur/weapon-charges#37]
The Toxic Blowpipe counter display for number of scale charges is permanently set to '?'. The number of darts in the blowpipe is accurately displayed still. The '?' for scale charges remains the same whether or not it is empty, only has darts, only has scales, or has both.

**Comment by geheur** [comment]
yep I broke it, wait for 0.6.1. sorry.

**Comment by Equanimous** [comment]
All good, thanks again for your work :)
