### ISSUE TITLE
Tome of Fire not updating

### ISSUE THREAD

**Issue by IsaacGraham** [geheur/weapon-charges#41]
I tried to update my tome of fire's charges overlay from the Weapon Charges plugin.
They recently (24/04/2024) changed the text to specify whether it is charged with Burnt or Searing pages.
Presumably this broke the functionality of using the Check function ingame to update the plugin's info.

![image](https://github.com/geheur/weapon-charges/assets/5593732/762d3a90-fa80-40dc-bc5f-92c9c822ff3e)

**Comment by geheur** [comment]
Is there one for removing a set amount of pages?
`(You remove [\S]+ pages? from the book. )?Your tome currently holds ([\d,]+) charges.` I have something like this in the plugin, what's the look like with the searing pages?

**Comment by IsaacGraham** [comment]
![20240507_014846](https://github.com/geheur/weapon-charges/assets/5593732/203a4301-388b-4f07-a6dd-104819a00625)

That message appears to be unchanged. Screenshot attached showing me removing 3 pages each from burnt and searing tomes.

I also checked a single page from searing, also in the screenshot. that seems unchanged as well.

**Comment by geheur** [comment]
Sorry for not getting to this. It will be in the next update and it will also show which page type you have (disableable on shift-right-click).
