### ISSUE TITLE
Blazing blowpipe not updating

### ISSUE THREAD

**Issue by VertiFatty** [geheur/weapon-charges#42]
The [Blazing blowpipe](https://oldschool.runescape.wiki/w/Blazing_blowpipe), the Toxic blowpipe with the Trailblazer reloaded blowpipe ornament kit, doesn't update when using the weapon. But it does update when you right click Check for charges.

**Comment by geheur** [comment]
I forgot about this unfortunately but it will be fixed in 0.6.6 when it releases.
