### ISSUE TITLE
Quiver ammo retention

### ISSUE THREAD

**Issue by IsaacGraham** [geheur/weapon-charges#43]
I noticed while using blowpipe with quiver, the display was decrementing ammo as if the quiver had no ammo retention capability. There does not appear to be a shift rightclick option on it as there is with the range cape.

I only have the blessed quiver, not the max cape variant or the unblessed one. as far as I am aware there are four variants.

Dizana's quiver (uncharged)
Dizana's quiver
Blessed dizana's quiver
Dizana's max cape

also (l) variants for each of the above.

It does not come with any ammo retention natively, but can inherit either the accumulator or assembler tier of retention.

**Comment by geheur** [comment]
Sounds like I missed one of the 4 dizana's quiver items, oops. It will be fixed in 0.6.7 along with ammo saving choice.
