### ISSUE TITLE
Abyssal Tentacle (or) missing

### ISSUE THREAD

**Issue by Soreil** [geheur/weapon-charges#5]
Leagues 3 added a new cosmetic kit reward for the abyssal tentacle. Currently it does not display charges. The regular abyssal tentacle works fine. From what I can tell the following constant should match the tentacle whip with ornament kit.

ABYSSAL_TENTACLE_OR
https://static.runelite.net/api/runelite-api/net/runelite/api/ItemID.html#ABYSSAL_WHIP_OR

**Comment by geheur** [comment]
Fix will be available when this PR is merged: https://github.com/runelite/plugin-hub/pull/2738.
