### ISSUE TITLE
Bowfa, Crystal, Equipment Expansion/Enhancement

### ISSUE THREAD

**Issue by MoonWolf125** [geheur/weapon-charges#6]
Stumbled across this plugin after being asked by some Runelite friends if there was a plugin that would provide an overlay for charges. Thanks for tackling that problem!

Has there been any interest in enhancing the plugin to account for items such as:
* Bow of faerdhinen
* Crystal armour

Or even expanding into equipment such as:
* Bonecrusher
* Ash Sanctifier
* Soul Bearer
* Diary Equipment

**Comment by geheur** [comment]
Bofa - I don't own one but it should be very easy to add.
crystal armor - might be hard to track if 0s from successful hits can reduce charges. I don't recall if it does.

non-combat gear - no plans atm and if I did it would likely be part of a different plugin because most of those aren't weapons ;).

**Comment by geheur** [comment]
I don't think crystal armor degrades on 0s, whether is was a hit or not.

Do you know if crystal armor ever puts messages in the chat on its own, like maybe every 500 charges lost or something?

**Comment by MoonWolf125** [comment]
- Crystal Armour
   - Unsuccessful hits **_do not_** degrade
   - Protected hits **_do not_** degrade (prayer)
   - Successful hits **_do_** degrade
   - Wearing an Elven Signet provides a 10% to **_not_** degrade

I was fortunate enough to recently upgrade to a Bowfa and full Crystal. I am almost out of charges and was planning on charging back up soon. I can charge back up to specific amounts and watch for messages while it degrades to help with the implementation.

Totally fair on the equipment, I can imagine that plugin being a sibling to this one.

**Comment by geheur** [comment]
yeah, if you could charge it up to like, 1100 and see if it says anything at 1000 that would be great. I tried to see if going through 2200 would make a message and it didn't. If it doesn't send a message at 1000 then it probably doesn't send any messages at all.

btw where did you get this list of crystal armor info?

**Comment by geheur** [comment]
oh and btw it's best if you have that "log data" checkbox ticked when the message happens, it prints messages out to the `client.log`.

In addition to periodic update message, I'd also need:
Check message (when you "check" on the item).
Any messages/dialogs that show up when you charge it.

btw if you have discord you can contact me there also: geheur#4508

**Comment by MoonWolf125** [comment]
Yeah, I'd be more than willing to charge Bowfa up in ~100 charge increments and test it out.

All of the crystal items have their degradation interactions listed on the wiki - wiki most likely got it from Jagex news/release/poll posts. Ex: [Crystal body degradation](https://oldschool.runescape.wiki/w/Crystal_body#Degradation)

Yeah, I figured `Log Data` was for dev/debug. I'll be sure to collect messages, dialogs, the logs and upload them here. I prefer to keep things off of Discord for tracking/reference, transparency, and uniformity within Github's system.

**Comment by MoonWolf125** [comment]
Wasn't able to get enough time in to work through charges, but here's a log snippet for Checking Bowfa and Crystal armour:
[BowfaCrystalArmourWeaponChargesCheck.log](https://github.com/geheur/weapon-charges/files/8855421/BowfaCrystalArmourWeaponChargesCheck.log)

**Comment by MoonWolf125** [comment]
Got called into Chambers with some friends. Hit the 100 charges remaining warning, here's the log snippet:
[BowfaChargesRemaining.log](https://github.com/geheur/weapon-charges/files/8857209/BowfaChargesRemaining.log)

**Comment by MoonWolf125** [comment]
Bowfa recharge log snippet:
[ChargeBowfa.log](https://github.com/geheur/weapon-charges/files/8857469/ChargeBowfa.log)

**Comment by MoonWolf125** [comment]
Alrighty. Some 250 Zulrah kc later and I think it's safe to say that this issue can be closed as completed (I'll leave that to you). The charges are being tracked for Bowfa and the Crystal armour pieces.

However; and this can be a separate ticket, I've noticed some drift in the charges on the Bowfa, Armour pieces, _**and**_ the trident. Anywhere from a charge or two to dozens of charges (depending on the item). It's the trident that makes me believe this is a wider issue than just the newest additions and thus can be a separate ticket.

**Comment by geheur** [comment]
I've seen items be off by a few but haven't really looked at why. I'm not surprised given how you have to go off of stuff like animations. This is one of the reasons I like weapons that update their progress in the chat when they reach certain charge levels. Can't get too desynced that way.

Which items were off by 1 or 2 vs which were off by dozens? And in which direction (too many or too few charges). And do you have any logs? Idk what would be in there tbh but might be interesting.

Anyways, I'll close this as completed.

**Comment by MoonWolf125** [comment]
If I remember correctly, the armour had the furthest drift and the weapons were only off by a few charges at most. When I have some time I'll gather logs and open up a new issue. It's not a super high priority on my list as just seeing the red/white overlay text is - in my opinion - more than enough to clue users in.
