### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by yoyodude4** [geheur/weapon-charges#7]
serp helm charges would be clutch!

**Comment by geheur** [comment]
Have you ever seen the serp helm, on its own, print out a message like "you only have 10% remaining!"?

**Comment by RHQ-Rusty** [comment]
Exploring this now @yoyodude4.

**Comment by RHQ-Rusty** [comment]
These are just some notes for myself and @geheur, as well as any other devs who may be interested in working on a PR. The wiki has some interesting insights into the [Serpentine Helmet's mechanics](https://oldschool.runescape.wiki/w/Serpentine_helm). It appears that, on combat beginning, 10 scales are deducted, and for every minute (100 in-game [ticks](https://oldschool.runescape.wiki/w/Tick_manipulation) as per the wiki, 90 in-game ticks as per Mod Ash (source pending) and @geheur's testing) the player is in combat, 10 more scales are deducted from the helmet.

The issue with this is determining when the player is in "combat" in accordance with the Serpentine Helmet's mechanics. What we know from the wiki is how long the checks are and how much is reduced, but not **what** the check is checking. Testing by @geheur seems to indicate it is triggered by an incoming or outgoing hitsplat landing (it could even be a 0 as long as it's not a splash).

This implies pseudo-code of the following:
```
check_combat = True if (incoming_hitsplat_land or outgoing_hitsplat_land) else False

while True
    if check_combat == True:
        scales -= 10
        combat = True
    if combat:
        while combat:
            sleep(tick_timer)
            if check_combat == True:
                scales -= 10
            else:
                combat = False
```

Obviously, further exploration needs to be done, and more testing will occur. I'll be working with @geheur to PR this and get it implemented. If things go smoothly with the Serpentine Helm, we may be able to do Barrows equipment as well, as the degradation is seemingly identical.

**Comment by geheur** [comment]
This has been merged.
